# agents/chat_agent.py

from agent.llm_client import LLMClient

class ChatAgent:
    """
    Handles conversational logic for the AI agent using an LLM.

    This agent is responsible for generating responses in a conversational context.
    It uses an LLM to generate human-like replies based on the user's input
    and the recent conversation history.
    """

    def __init__(self):
        """
        Initializes the ChatAgent with an LLM client.
        """
        self.llm_client = LLMClient()

    def execute(self, user_input, conversation_history=None):
        """
        Executes the chat logic based on user input and conversation history.

        Args:
            user_input (str): The text input from the user.
            conversation_history (list, optional): A list of previous messages.

        Returns:
            str: A text response generated by the LLM.
        """
        print(f"[ChatAgent] Processing input: '{user_input}' with history.")

        # Construct a prompt for the LLM
        prompt = self._construct_prompt(user_input, conversation_history)

        # Generate a response using the LLM
        response = self.llm_client.generate_response(prompt)

        print(f"[ChatAgent] Generated response: '{response}'")
        return response

    def _construct_prompt(self, user_input, history):
        """
        Constructs a detailed prompt for the LLM, including history.
        """
        prompt = "You are a helpful AI assistant. Continue the conversation.\n\n"

        if history:
            prompt += "Conversation History:\n"
            for message in history:
                role = "User" if message.get('role') == 'user' else "Assistant"
                prompt += f"- {role}: {message.get('content')}\n"

        prompt += f"\nNew User Message: {user_input}\nAssistant:"
        return prompt

if __name__ == '__main__':
    # Example usage for testing the ChatAgent directly

    chat_agent = ChatAgent()

    # Test case 1: A simple greeting (no history)
    response1 = chat_agent.execute("Hello there!")
    print(f"User: 'Hello there!'\nAgent: '{response1}'\n")

    # Test case 2: A follow-up question with history
    history = [
        {"role": "user", "content": "What's the best thing about Switzerland?"},
        {"role": "assistant", "content": "The flag is a big plus."}
    ]
    response2 = chat_agent.execute("Why is that?", conversation_history=history)
    print(f"User: 'Why is that?' (with history)\nAgent: '{response2}'\n")
